using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TwilioSdk.Core;
using TwilioSdk.Core.ErrorResponse;
using TwilioSdk.Core.Exceptions;
using TwilioSdk.Core.Models;
using TwilioSdk.Core.Request;
using TwilioSdk.Core.Response;
using TwilioSdk.Models;

namespace TwilioSdk.Api;

public sealed class InsightsV1ConferenceParticipant
{
    private readonly RawClient _rawClient;
    private readonly Server _server;
    private readonly AuthSchemes _auth;

    internal InsightsV1ConferenceParticipant(RawClient rawClient, Server server, AuthSchemes auth)
    {
        _rawClient = rawClient;
        _server = server;
        _auth = auth;
    }

    /// <summary>
    /// Get a specific Conference Participant Summary for a Conference.
    /// </summary>
    /// <param name="conferenceSid">The unique SID identifier of the Conference.</param>
    /// <param name="participantSid">The unique SID identifier of the Participant.</param>
    /// <param name="events">Conference events generated by application or participant activity; e.g. <c>hold</c>, <c>mute</c>, etc.</param>
    /// <param name="metrics">Object. Contains participant call quality metrics.</param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="InsightsV1ConferenceConferenceParticipant"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Get a specific Conference Participant Summary for a Conference.
    /// </remarks>
    public Task<InsightsV1ConferenceConferenceParticipant> FetchConferenceParticipant(string conferenceSid,
        string participantSid,
        string? events,
        string? metrics,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default14("/v1/Conferences/{ConferenceSid}/Participants/{ParticipantSid}"),
            [new TemplateParam("ConferenceSid", conferenceSid), new TemplateParam("ParticipantSid", participantSid)],
            [new Param("Events", events), new Param("Metrics", metrics)],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<InsightsV1ConferenceConferenceParticipant>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Get a list of Conference Participants Summaries for a Conference.
    /// </summary>
    /// <param name="conferenceSid">The unique SID identifier of the Conference.</param>
    /// <param name="participantSid">The unique SID identifier of the Participant.</param>
    /// <param name="label">User-specified label for a participant.</param>
    /// <param name="events">Conference events generated by application or participant activity; e.g. <c>hold</c>, <c>mute</c>, etc.</param>
    /// <param name="pageSize">How many resources to return in each list page. The default is 50, and the maximum is 1000.</param>
    /// <param name="page">The page index. This value is simply for client state.</param>
    /// <param name="pageToken">The page token. This is provided by the API.</param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="ListConferenceParticipantResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Get a list of Conference Participants Summaries for a Conference.
    /// </remarks>
    public Task<ListConferenceParticipantResponse> ListConferenceParticipant(string conferenceSid,
        string? participantSid,
        string? label,
        string? events,
        long? pageSize,
        int? page,
        string? pageToken,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default14("/v1/Conferences/{ConferenceSid}/Participants"),
            [new TemplateParam("ConferenceSid", conferenceSid)],
            [new Param("ParticipantSid", participantSid),
                new Param("Label", label),
                new Param("Events", events),
                new Param("PageSize", pageSize),
                new Param("Page", page),
                new Param("PageToken", pageToken)],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<ListConferenceParticipantResponse>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);
}
