using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TwilioSdk.Core;
using TwilioSdk.Core.ErrorResponse;
using TwilioSdk.Core.Exceptions;
using TwilioSdk.Core.Models;
using TwilioSdk.Core.Request;
using TwilioSdk.Core.Response;
using TwilioSdk.Models;
using TwilioSdk.Models.Enums;

namespace TwilioSdk.Api;

public sealed class VerifyV2NewFactor
{
    private readonly RawClient _rawClient;
    private readonly Server _server;
    private readonly AuthSchemes _auth;

    internal VerifyV2NewFactor(RawClient rawClient, Server server, AuthSchemes auth)
    {
        _rawClient = rawClient;
        _server = server;
        _auth = auth;
    }

    /// <summary>
    /// Create a new Factor for the Entity
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Factor. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="friendlyName"></param>
    /// <param name="factorType"></param>
    /// <param name="bindingAlg"></param>
    /// <param name="bindingPublicKey"></param>
    /// <param name="configAppId"></param>
    /// <param name="configNotificationPlatform"></param>
    /// <param name="configNotificationToken"></param>
    /// <param name="configSdkVersion"></param>
    /// <param name="bindingSecret"></param>
    /// <param name="configTimeStep"></param>
    /// <param name="configSkew"></param>
    /// <param name="configCodeLength"></param>
    /// <param name="configAlg"></param>
    /// <param name="metadata"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="VerifyV2ServiceEntityNewFactor"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Create a new Factor for the Entity
    /// </remarks>
    public Task<VerifyV2ServiceEntityNewFactor> CreateNewFactor(string serviceSid,
        string identity,
        string friendlyName,
        NewFactorEnumFactorTypes factorType,
        string? bindingAlg,
        string? bindingPublicKey,
        string? configAppId,
        NewFactorEnumNotificationPlatforms? configNotificationPlatform,
        string? configNotificationToken,
        string? configSdkVersion,
        string? bindingSecret,
        int? configTimeStep,
        int? configSkew,
        int? configCodeLength,
        NewFactorEnumTotpAlgorithms? configAlg,
        object? metadata,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors"),
            [new TemplateParam("ServiceSid", serviceSid), new TemplateParam("Identity", identity)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            FormUrlEncodedRequest.Create([new Param("FriendlyName", friendlyName),
                    new Param("FactorType", factorType),
                    new Param("Binding.Alg", bindingAlg),
                    new Param("Binding.PublicKey", bindingPublicKey),
                    new Param("Config.AppId", configAppId),
                    new Param("Config.NotificationPlatform", configNotificationPlatform),
                    new Param("Config.NotificationToken", configNotificationToken),
                    new Param("Config.SdkVersion", configSdkVersion),
                    new Param("Binding.Secret", bindingSecret),
                    new Param("Config.TimeStep", configTimeStep),
                    new Param("Config.Skew", configSkew),
                    new Param("Config.CodeLength", configCodeLength),
                    new Param("Config.Alg", configAlg),
                    new Param("Metadata", metadata)]),
            JsonResponse.Create<VerifyV2ServiceEntityNewFactor>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Create a new Passkeys Factor for the Entity
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="body"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="V2ServicesPasskeysFactorsResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Create a new Passkeys Factor for the Entity
    /// </remarks>
    public Task<V2ServicesPasskeysFactorsResponse> CreateNewFactorPasskey(string serviceSid,
        CreateNewPasskeysFactorRequest body,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Passkeys/Factors"),
            [new TemplateParam("ServiceSid", serviceSid)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            JsonRequest.Create(body),
            JsonResponse.Create<V2ServicesPasskeysFactorsResponse>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);
}
