using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TwilioSdk.Core;
using TwilioSdk.Core.ErrorResponse;
using TwilioSdk.Core.Exceptions;
using TwilioSdk.Core.Models;
using TwilioSdk.Core.Request;
using TwilioSdk.Core.Response;
using TwilioSdk.Models;
using TwilioSdk.Models.Enums;

namespace TwilioSdk.Api;

public sealed class VerifyV2Factor
{
    private readonly RawClient _rawClient;
    private readonly Server _server;
    private readonly AuthSchemes _auth;

    internal VerifyV2Factor(RawClient rawClient, Server server, AuthSchemes auth)
    {
        _rawClient = rawClient;
        _server = server;
        _auth = auth;
    }

    /// <summary>
    /// Delete a specific Factor.
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Factor. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="sid">A 34 character string that uniquely identifies this Factor.</param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Delete a specific Factor.
    /// </remarks>
    public Task DeleteFactor(string serviceSid,
        string identity,
        string sid,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            [new TemplateParam("ServiceSid", serviceSid),
                new TemplateParam("Identity", identity),
                new TemplateParam("Sid", sid)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Delete,
            EmptyBody.Instance,
            VoidResponse.Instance,
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Fetch a specific Factor.
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Factor. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="sid">A 34 character string that uniquely identifies this Factor.</param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="VerifyV2ServiceEntityFactor"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Fetch a specific Factor.
    /// </remarks>
    public Task<VerifyV2ServiceEntityFactor> FetchFactor(string serviceSid,
        string identity,
        string sid,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            [new TemplateParam("ServiceSid", serviceSid),
                new TemplateParam("Identity", identity),
                new TemplateParam("Sid", sid)],
            [],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<VerifyV2ServiceEntityFactor>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Retrieve a list of all Factors for an Entity.
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Factors. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="pageSize">How many resources to return in each list page. The default is 50, and the maximum is 1000.</param>
    /// <param name="page">The page index. This value is simply for client state.</param>
    /// <param name="pageToken">The page token. This is provided by the API.</param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="ListFactorResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Retrieve a list of all Factors for an Entity.
    /// </remarks>
    public Task<ListFactorResponse> ListFactor(string serviceSid,
        string identity,
        long? pageSize,
        int? page,
        string? pageToken,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors"),
            [new TemplateParam("ServiceSid", serviceSid), new TemplateParam("Identity", identity)],
            [new Param("PageSize", pageSize), new Param("Page", page), new Param("PageToken", pageToken)],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<ListFactorResponse>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Update a specific Factor. This endpoint can be used to Verify a Factor if passed an <c>AuthPayload</c> param.
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Factor. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="sid">A 34 character string that uniquely identifies this Factor.</param>
    /// <param name="authPayload"></param>
    /// <param name="friendlyName"></param>
    /// <param name="configNotificationToken"></param>
    /// <param name="configSdkVersion"></param>
    /// <param name="configTimeStep"></param>
    /// <param name="configSkew"></param>
    /// <param name="configCodeLength"></param>
    /// <param name="configAlg"></param>
    /// <param name="configNotificationPlatform"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="VerifyV2ServiceEntityFactor"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Update a specific Factor. This endpoint can be used to Verify a Factor if passed an <c>AuthPayload</c> param.
    /// </remarks>
    public Task<VerifyV2ServiceEntityFactor> UpdateFactor(string serviceSid,
        string identity,
        string sid,
        string? authPayload,
        string? friendlyName,
        string? configNotificationToken,
        string? configSdkVersion,
        int? configTimeStep,
        int? configSkew,
        int? configCodeLength,
        FactorEnumTotpAlgorithms? configAlg,
        string? configNotificationPlatform,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Factors/{Sid}"),
            [new TemplateParam("ServiceSid", serviceSid),
                new TemplateParam("Identity", identity),
                new TemplateParam("Sid", sid)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            FormUrlEncodedRequest.Create([new Param("AuthPayload", authPayload),
                    new Param("FriendlyName", friendlyName),
                    new Param("Config.NotificationToken", configNotificationToken),
                    new Param("Config.SdkVersion", configSdkVersion),
                    new Param("Config.TimeStep", configTimeStep),
                    new Param("Config.Skew", configSkew),
                    new Param("Config.CodeLength", configCodeLength),
                    new Param("Config.Alg", configAlg),
                    new Param("Config.NotificationPlatform", configNotificationPlatform)]),
            JsonResponse.Create<VerifyV2ServiceEntityFactor>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);
}
