using System.Collections.Generic;
using System.Text.Json.Serialization;
using TwilioSdk.Core.Models;
using TwilioSdk.Models.Enums;

namespace TwilioSdk.Models;

/// <summary>
/// The result of a WebAuthn credential registration via <c>navigator.credentials.create()</c>, as specified in <see href="https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse">AuthenticatorAttestationResponse</see>.
/// </summary>
public record ResponseModel
{
    /// <summary>
    /// The authenticator data and an attestation statement for a new key pair generated by the authenticator.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("attestationObject")]
    public string? AttestationObject { get; init; }

    /// <summary>
    /// This property contains the JSON-compatible serialization of the data passed from the browser to the authenticator in order to generate this credential.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("clientDataJSON")]
    public string? ClientDataJson { get; init; }

    /// <summary>
    /// An array of strings providing hints as to the methods the client could use to communicate with the relevant authenticator of the public key credential to retrieve.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("transports")]
    public IReadOnlyList<Transport>? Transports { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
