<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>Microsoft.eShopWeb.MaxioSubscriptionTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.runner.console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PublicApi\PublicApi.csproj" />
    <ProjectReference Include="..\..\src\MaxioAdvancedBilling\MaxioAdvancedBilling.csproj" />
  </ItemGroup>

</Project>
