using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Twilio.Core;
using Twilio.Core.ErrorResponse;
using Twilio.Core.Exceptions;
using Twilio.Core.Models;
using Twilio.Core.Request;
using Twilio.Core.Response;
using Twilio.Models;
using Twilio.Models.Enums;

namespace Twilio.Api;

public sealed class VerifyV2Challenge
{
    private readonly RawClient _rawClient;
    private readonly Server _server;
    private readonly AuthSchemes _auth;

    internal VerifyV2Challenge(RawClient rawClient, Server server, AuthSchemes auth)
    {
        _rawClient = rawClient;
        _server = server;
        _auth = auth;
    }

    /// <summary>
    /// Create a new Challenge for the Factor
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="factorSid"></param>
    /// <param name="expirationDate"></param>
    /// <param name="detailsMessage"></param>
    /// <param name="detailsFields"></param>
    /// <param name="hiddenDetails"></param>
    /// <param name="authPayload"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="VerifyV2ServiceEntityChallenge"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Create a new Challenge for the Factor
    /// </remarks>
    public Task<VerifyV2ServiceEntityChallenge> CreateChallenge(string serviceSid,
        string identity,
        string factorSid,
        DateTimeOffset? expirationDate,
        string? detailsMessage,
        IReadOnlyList<object>? detailsFields,
        object? hiddenDetails,
        string? authPayload,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges"),
            [new TemplateParam("ServiceSid", serviceSid), new TemplateParam("Identity", identity)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            FormUrlEncodedRequest.Create([new Param("FactorSid", factorSid),
                    new Param("ExpirationDate", expirationDate),
                    new Param("Details.Message", detailsMessage),
                    new Param("Details.Fields", detailsFields),
                    new Param("HiddenDetails", hiddenDetails),
                    new Param("AuthPayload", authPayload)]),
            JsonResponse.Create<VerifyV2ServiceEntityChallenge>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Fetch a specific Challenge.
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Challenges. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="sid">A 34 character string that uniquely identifies this Challenge.</param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="VerifyV2ServiceEntityChallenge"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Fetch a specific Challenge.
    /// </remarks>
    public Task<VerifyV2ServiceEntityChallenge> FetchChallenge(string serviceSid,
        string identity,
        string sid,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}"),
            [new TemplateParam("ServiceSid", serviceSid),
                new TemplateParam("Identity", identity),
                new TemplateParam("Sid", sid)],
            [],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<VerifyV2ServiceEntityChallenge>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Retrieve a list of all Challenges for a Factor.
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="factorSid">The unique SID identifier of the Factor.</param>
    /// <param name="status">The Status of the Challenges to fetch. One of <c>pending</c>, <c>expired</c>, <c>approved</c> or <c>denied</c>.</param>
    /// <param name="order">The desired sort order of the Challenges list. One of <c>asc</c> or <c>desc</c> for ascending and descending respectively. Defaults to <c>asc</c>.</param>
    /// <param name="pageSize">How many resources to return in each list page. The default is 50, and the maximum is 1000.</param>
    /// <param name="page">The page index. This value is simply for client state.</param>
    /// <param name="pageToken">The page token. This is provided by the API.</param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="ListChallengeResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Retrieve a list of all Challenges for a Factor.
    /// </remarks>
    public Task<ListChallengeResponse> ListChallenge(string serviceSid,
        string identity,
        string? factorSid,
        ChallengeEnumChallengeStatuses? status,
        ChallengeEnumListOrders? order,
        long? pageSize,
        int? page,
        string? pageToken,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges"),
            [new TemplateParam("ServiceSid", serviceSid), new TemplateParam("Identity", identity)],
            [new Param("FactorSid", factorSid),
                new Param("Status", status),
                new Param("Order", order),
                new Param("PageSize", pageSize),
                new Param("Page", page),
                new Param("PageToken", pageToken)],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<ListChallengeResponse>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);

    /// <summary>
    /// Verify a specific Challenge.
    /// </summary>
    /// <param name="serviceSid">The unique SID identifier of the Service.</param>
    /// <param name="identity">Customer unique identity for the Entity owner of the Challenge. This identifier should be immutable, not PII, length between 8 and 64 characters, and generated by your external system, such as your user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.</param>
    /// <param name="sid">A 34 character string that uniquely identifies this Challenge.</param>
    /// <param name="authPayload"></param>
    /// <param name="metadata"></param>
    /// <param name="requestOptions">Per-request options, such as an overriding log level for this call</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="VerifyV2ServiceEntityChallenge"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Verify a specific Challenge.
    /// </remarks>
    public Task<VerifyV2ServiceEntityChallenge> UpdateChallenge(string serviceSid,
        string identity,
        string sid,
        string? authPayload,
        object? metadata,
        RequestOptions? requestOptions = null,
        CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default3("/v2/Services/{ServiceSid}/Entities/{Identity}/Challenges/{Sid}"),
            [new TemplateParam("ServiceSid", serviceSid),
                new TemplateParam("Identity", identity),
                new TemplateParam("Sid", sid)],
            [],
            [new HeaderParam("Idempotency-Key", Guid.NewGuid())],
            HttpMethod.Post,
            FormUrlEncodedRequest.Create([new Param("AuthPayload", authPayload), new Param("Metadata", metadata)]),
            JsonResponse.Create<VerifyV2ServiceEntityChallenge>(),
            RawErrorResponse.Instance,
            [_auth.AccountSidAuthToken],
            requestOptions,
            ct);
}
