using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.eShopWeb.ApplicationCore.Entities;
using Microsoft.eShopWeb.ApplicationCore.Entities.OrderAggregate;
using Microsoft.eShopWeb.Infrastructure.Data;

namespace Microsoft.eShopWeb.PublicApi.Payments;

public static class PaymentEndpoints
{
 public static void MapPaymentEndpoints(this WebApplication app)
 {
  var shopper = new AuthorizeAttribute { AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme };
  app.MapPost("api/orders", CreateOrder).RequireAuthorization(shopper);
  app.MapPost("api/orders/{orderId:int}/pay", PayOrder).RequireAuthorization(shopper);
  app.MapPost("api/orders/{orderId:int}/fulfil", Fulfil).RequireAuthorization(new AuthorizeAttribute{Roles=BlazorShared.Authorization.Constants.Roles.ADMINISTRATORS});
  app.MapPost("api/orders/{orderId:int}/cancel", Cancel).RequireAuthorization(new AuthorizeAttribute{Roles=BlazorShared.Authorization.Constants.Roles.ADMINISTRATORS});
  app.MapPost("api/orders/{orderId:int}/refunds", Refund).RequireAuthorization(shopper);
  app.MapGet("api/my-orders", MyOrders).RequireAuthorization(shopper);
  app.MapPost("api/payment-methods", SaveMethod).RequireAuthorization(shopper);
  app.MapGet("api/payment-methods", ListMethods).RequireAuthorization(shopper);
  app.MapDelete("api/payment-methods/{id:int}", DeleteMethod).RequireAuthorization(shopper);
  app.MapGet("api/reconciliation", Reconciliation).RequireAuthorization(new AuthorizeAttribute{Roles=BlazorShared.Authorization.Constants.Roles.ADMINISTRATORS});
 }
 static string User(HttpContext h)=>h.User.FindFirstValue(ClaimTypes.Name)??throw new UnauthorizedAccessException();
 static async Task<IResult> CreateOrder(CreateOrderRequest r,HttpContext h,CatalogContext db, CancellationToken ct){
  if(r.Items is null||r.Items.Count==0) return Results.BadRequest("At least one item is required.");
  var ids=r.Items.Select(x=>x.CatalogItemId).Distinct().ToArray(); var cats=await db.CatalogItems.Where(x=>ids.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct); if(cats.Count!=ids.Length) return Results.BadRequest("One or more catalog items do not exist.");
  var items=new List<OrderItem>(); foreach(var line in r.Items){if(line.Quantity<1) return Results.BadRequest("Quantity must be positive."); var c=cats[line.CatalogItemId]; items.Add(new OrderItem(new CatalogItemOrdered(c.Id,c.Name,c.PictureUri),c.Price,line.Quantity));}
  var order=new Order(User(h),new Address(r.Shipping.Street,r.Shipping.City,r.Shipping.State??"",r.Shipping.Country,r.Shipping.ZipCode),items); db.Orders.Add(order); await db.SaveChangesAsync(ct); return Results.Created($"api/orders/{order.Id}",new{orderId=order.Id,status=order.Status.ToString(),total=order.Total()});
 }
 static async Task<IResult> PayOrder(int orderId,PayRequest r,HttpContext h,CatalogContext db,PayPalClient pp,CancellationToken ct){
  var uid=User(h); var o=await db.Orders.Include(x=>x.OrderItems).SingleOrDefaultAsync(x=>x.Id==orderId&&x.BuyerId==uid,ct); if(o is null)return Results.NotFound(); if(o.Status!=OrderStatus.AwaitingPayment)return Results.Ok(new{orderId,status=o.Status.ToString()});
  var p=await db.OrderPayments.SingleOrDefaultAsync(x=>x.OrderId==orderId,ct)??new OrderPayment(orderId,uid,o.Total(),pp.Options.Currency); if(p.Id==0)db.OrderPayments.Add(p);
  object source; if(r.PaymentMethodId is not null){var m=await db.PaymentMethods.SingleOrDefaultAsync(x=>x.Id==r.PaymentMethodId&&x.BuyerId==uid,ct);if(m is null)return Results.BadRequest("Payment method is not available.");source=new{card=new{vault_id=m.PayPalTokenId}};} else {if(r.Card is null)return Results.BadRequest("Provide card details or paymentMethodId."); source=new{card=new{number=r.Card.Number,expiry=r.Card.Expiry,name=r.Card.Name,billing_address=new{address_line_1=r.Card.BillingAddress?.Street,address_line_2=(string?)null,admin_area_1=r.Card.BillingAddress?.State,admin_area_2=r.Card.BillingAddress?.City,postal_code=r.Card.BillingAddress?.ZipCode,country_code=r.Card.BillingAddress?.Country},attributes=new{verification=new{method="SCA_WHEN_REQUIRED"}}}};}
  using var created=await pp.Send(HttpMethod.Post,"/v2/checkout/orders",new{intent="AUTHORIZE",purchase_units=new[]{new{reference_id=$"eshop-order-{orderId}",invoice_id=p.InvoiceId,amount=new{currency_code=pp.Options.Currency,value=o.Total().ToString("0.00",CultureInfo.InvariantCulture)}}},payment_source=source},$"eshop-order-{orderId}",ct); if(created.RootElement.TryGetProperty("status",out var st)&&st.GetString()=="PAYER_ACTION_REQUIRED")return Results.UnprocessableEntity(new{message="PayPal requires browser approval; this headless integration cannot continue."}); var paypalId=created.RootElement.GetProperty("id").GetString()!;
  using var authorized=await pp.Send(HttpMethod.Post,$"/v2/checkout/orders/{paypalId}/authorize",new{},$"eshop-authorize-{orderId}",ct); if(authorized.RootElement.TryGetProperty("status",out st)&&st.GetString()=="PAYER_ACTION_REQUIRED")return Results.UnprocessableEntity(new{message="PayPal requires browser approval; this headless integration cannot continue."}); var a=authorized.RootElement.GetProperty("purchase_units")[0].GetProperty("payments").GetProperty("authorizations")[0]; p.Authorized(paypalId,a.GetProperty("id").GetString()!,a.GetProperty("status").GetString()!,Date(a,"expiration_time")); o.MarkAuthorized(); await db.SaveChangesAsync(ct); return Results.Ok(new{orderId,status=o.Status.ToString(),payment=new{authorizationId=p.AuthorizationId,status=p.AuthorizationStatus,amount=p.Amount,currency=p.Currency}});
 }
 static async Task<IResult> Fulfil(int orderId,HttpContext h,CatalogContext db,PayPalClient pp,CancellationToken ct){var o=await db.Orders.SingleOrDefaultAsync(x=>x.Id==orderId,ct);if(o is null)return Results.NotFound();var p=await db.OrderPayments.SingleOrDefaultAsync(x=>x.OrderId==orderId,ct);if(p is null||p.Status!="AUTHORIZED")return Results.Conflict(new{message="Order is not ready for fulfilment; it must have an active authorization."}); try{if(p.AuthorizationExpiresUtc<=DateTimeOffset.UtcNow.AddMinutes(1)){using var re=await pp.Send(HttpMethod.Post,$"/v2/payments/authorizations/{p.AuthorizationId}/reauthorize",new{},$"eshop-reauthorize-{orderId}-{p.AuthorizationId}",ct);var na=re.RootElement; p.Reauthorized(na.GetProperty("id").GetString()!,na.GetProperty("status").GetString()!,Date(na,"expiration_time"));} using var cap=await pp.Send(HttpMethod.Post,$"/v2/payments/authorizations/{p.AuthorizationId}/capture",new{amount=new{currency_code=p.Currency,value=p.Amount.ToString("0.00",CultureInfo.InvariantCulture)},invoice_id=$"ESHOP-{orderId}",final_capture=true},$"eshop-capture-{orderId}",ct);var c=cap.RootElement;var br=c.GetProperty("seller_receivable_breakdown");p.Captured(c.GetProperty("id").GetString()!,c.GetProperty("status").GetString()!,Money(c.GetProperty("amount")),MoneyOrNull(br,"paypal_fee"),MoneyOrNull(br,"net_amount"));o.MarkFulfilled();await db.SaveChangesAsync(ct);return Results.Ok(new{orderId,status=o.Status.ToString(),capturedAmount=p.CapturedAmount,payPalFee=p.PayPalFee,netAmount=p.NetAmount,captureId=p.CaptureId});}catch(PayPalException ex){return Results.UnprocessableEntity(new{message=$"Fulfilment could not renew or capture the PayPal authorization. Operator action: obtain a new payment authorization and retry. PayPal: {ex.Message}"});}}
 static async Task<IResult> Cancel(int orderId,CatalogContext db,PayPalClient pp,CancellationToken ct){var o=await db.Orders.SingleOrDefaultAsync(x=>x.Id==orderId,ct);if(o is null)return Results.NotFound();if(o.Status==OrderStatus.Fulfilled)return Results.Conflict("Fulfilled orders must be refunded.");var p=await db.OrderPayments.SingleOrDefaultAsync(x=>x.OrderId==orderId,ct);if(p?.Status=="AUTHORIZED"){using var v=await pp.Send(HttpMethod.Post,$"/v2/payments/authorizations/{p.AuthorizationId}/void",new{},$"eshop-void-{orderId}",ct);p.Voided(v.RootElement.GetProperty("status").GetString()!);}o.MarkCancelled();await db.SaveChangesAsync(ct);return Results.Ok(new{orderId,status=o.Status.ToString()});}
 static async Task<IResult> Refund(int orderId,RefundRequest r,HttpContext h,CatalogContext db,PayPalClient pp,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.IdempotencyKey))return Results.BadRequest("Idempotency-Key is required in the request body.");var uid=User(h);var o=await db.Orders.SingleOrDefaultAsync(x=>x.Id==orderId&&x.BuyerId==uid,ct);if(o is null)return Results.NotFound();var p=await db.OrderPayments.SingleOrDefaultAsync(x=>x.OrderId==orderId,ct);if(p is null||p.Status!="CAPTURED")return Results.Conflict("Only captured orders can be refunded.");var old=await db.OrderRefunds.SingleOrDefaultAsync(x=>x.OrderId==orderId&&x.IdempotencyKey==r.IdempotencyKey,ct);if(old is not null)return Results.Ok(new{refundId=old.Id,status=old.Status,payPalRefundId=old.PayPalRefundId});var amount=r.Amount??(p.CapturedAmount!.Value-(await db.OrderRefunds.Where(x=>x.OrderId==orderId&&x.Status=="COMPLETED").SumAsync(x=>(decimal?)x.Amount,ct)??0));var refunded=await db.OrderRefunds.Where(x=>x.OrderId==orderId&&x.Status=="COMPLETED").SumAsync(x=>(decimal?)x.Amount,ct)??0;if(amount<=0||refunded+amount>p.CapturedAmount)return Results.BadRequest("Refund amount exceeds the captured amount remaining.");var rr=new OrderRefund(orderId,uid,r.IdempotencyKey,amount);db.OrderRefunds.Add(rr);using var res=await pp.Send(HttpMethod.Post,$"/v2/payments/captures/{p.CaptureId}/refund",new{amount=new{currency_code=p.Currency,value=amount.ToString("0.00",CultureInfo.InvariantCulture)},invoice_id=$"ESHOP-{orderId}"},r.IdempotencyKey,ct);rr.Completed(res.RootElement.GetProperty("id").GetString()!,res.RootElement.GetProperty("status").GetString()!);await db.SaveChangesAsync(ct);return Results.Ok(new{refundId=rr.Id,status=rr.Status,payPalRefundId=rr.PayPalRefundId,amount});}
 static async Task<IResult> MyOrders(HttpContext h,CatalogContext db,CancellationToken ct){var uid=User(h);var os=await db.Orders.Where(x=>x.BuyerId==uid).OrderByDescending(x=>x.OrderDate).ToListAsync(ct);var ps=await db.OrderPayments.Where(x=>x.BuyerId==uid).ToDictionaryAsync(x=>x.OrderId,ct);return Results.Ok(os.Select(o=>new{orderId=o.Id,o.OrderDate,status=o.Status.ToString(),total=o.Total(),payment=ps.TryGetValue(o.Id,out var p)?new{p.Status,p.AuthorizationId,p.AuthorizationStatus,p.CaptureId,p.CaptureStatus,p.CapturedAmount,p.PayPalFee,p.NetAmount}:null}));}
 static async Task<IResult> SaveMethod(SaveCardRequest r,HttpContext h,CatalogContext db,PayPalClient pp,CancellationToken ct){if(r.Card is null)return Results.BadRequest("Card is required.");var uid=User(h);using var setup=await pp.Send(HttpMethod.Post,"/v3/vault/setup-tokens",new{payment_source=new{card=new{number=r.Card.Number,expiry=r.Card.Expiry,name=r.Card.Name,billing_address=new{address_line_1=r.Card.BillingAddress?.Street,admin_area_1=r.Card.BillingAddress?.State,admin_area_2=r.Card.BillingAddress?.City,postal_code=r.Card.BillingAddress?.ZipCode,country_code=r.Card.BillingAddress?.Country}}}},"eshop-vault-setup-"+Guid.NewGuid().ToString("N"),ct);if(setup.RootElement.TryGetProperty("links",out var links)&&links.EnumerateArray().Any(x=>x.GetProperty("rel").GetString()=="approve"))return Results.UnprocessableEntity(new{message="PayPal requires browser approval; this headless integration cannot save this card."});var setupId=setup.RootElement.GetProperty("id").GetString()!;using var token=await pp.Send(HttpMethod.Post,"/v3/vault/payment-tokens",new{payment_source=new{token=new{id=setupId,type="SETUP_TOKEN"}}},"eshop-vault-token-"+Guid.NewGuid().ToString("N"),ct);var root=token.RootElement;var card=root.GetProperty("payment_source").GetProperty("card");var m=new PaymentMethod(uid,root.GetProperty("id").GetString()!,card.GetProperty("brand").GetString()??"UNKNOWN",card.GetProperty("last_digits").GetString()??"",card.GetProperty("expiry").GetString()??r.Card.Expiry);db.PaymentMethods.Add(m);await db.SaveChangesAsync(ct);return Results.Created($"api/payment-methods/{m.Id}",new{paymentMethodId=m.Id,brand=m.Brand,lastFour=m.LastFour,expiry=m.Expiry});}
 static async Task<IResult> ListMethods(HttpContext h,CatalogContext db,CancellationToken ct)=>Results.Ok(await db.PaymentMethods.Where(x=>x.BuyerId==User(h)).OrderByDescending(x=>x.CreatedUtc).Select(x=>new{paymentMethodId=x.Id,brand=x.Brand,lastFour=x.LastFour,expiry=x.Expiry}).ToListAsync(ct));
 static async Task<IResult> DeleteMethod(int id,HttpContext h,CatalogContext db,PayPalClient pp,CancellationToken ct){var m=await db.PaymentMethods.SingleOrDefaultAsync(x=>x.Id==id&&x.BuyerId==User(h),ct);if(m is null)return Results.NotFound();using var r=await pp.Send(HttpMethod.Delete,$"/v3/vault/payment-tokens/{m.PayPalTokenId}",null,"eshop-vault-delete-"+m.Id,ct);db.PaymentMethods.Remove(m);await db.SaveChangesAsync(ct);return Results.NoContent();}
 static async Task<IResult> Reconciliation(DateTimeOffset from,DateTimeOffset to,PayPalClient pp,CancellationToken ct){if(to<=from)return Results.BadRequest("to must be after from.");var all=new List<JsonElement>();for(var s=from;s<to;){var e=s.AddDays(31);if(e>to)e=to;for(var page=1;;page++){var path=$"/v1/reporting/transactions?start_date={Uri.EscapeDataString(s.ToUniversalTime().ToString("O"))}&end_date={Uri.EscapeDataString(e.ToUniversalTime().ToString("O"))}&fields=all&page_size=500&page={page}";using var d=await pp.Send(HttpMethod.Get,path,null,$"eshop-reconciliation-{s:yyyyMMdd}-{page}",ct);if(!d.RootElement.TryGetProperty("transaction_details",out var rows)||rows.GetArrayLength()==0)break;all.AddRange(rows.EnumerateArray().Select(x=>x.Clone()));if(!d.RootElement.TryGetProperty("total_items",out var total)||page*500>=total.GetInt32())break;}s=e;}return Results.Ok(all.Select(x=>new{paypalTransaction=x.TryGetProperty("transaction_info",out var i)&&i.TryGetProperty("transaction_id",out var id)?id.GetString():null,invoiceId=x.TryGetProperty("transaction_info",out i)&&i.TryGetProperty("invoice_id",out var inv)?inv.GetString():null,status=x.TryGetProperty("transaction_info",out i)&&i.TryGetProperty("transaction_status",out var ss)?ss.GetString():null,raw=x}));}
 static DateTimeOffset? Date(JsonElement e,string p)=>e.TryGetProperty(p,out var x)&&DateTimeOffset.TryParse(x.GetString(),out var d)?d:null;
 static decimal Money(JsonElement e)=>decimal.Parse(e.GetProperty("value").GetString()!,CultureInfo.InvariantCulture);
 static decimal? MoneyOrNull(JsonElement e,string p)=>e.TryGetProperty(p,out var x)?Money(x):null;
}
public record CreateOrderRequest(List<OrderLine> Items,ShippingAddress Shipping); public record OrderLine(int CatalogItemId,int Quantity); public record ShippingAddress(string Street,string City,string? State,string Country,string ZipCode); public record PayRequest(CardInput? Card,int? PaymentMethodId); public record SaveCardRequest(CardInput Card); public record RefundRequest(decimal? Amount,string IdempotencyKey); public record CardInput(string Number,string Expiry,string Name,ShippingAddress? BillingAddress);
